# Generated by Django 2.2.16 on 2020-10-17 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Phones',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('phone_name', models.CharField(max_length=1024)),
                ('phone_url', models.CharField(max_length=1024)),
            ],
            options={
                'db_table': 'phones',
            },
        ),
        migrations.CreateModel(
            name='PhonesWithOpinions',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('phone_name', models.CharField(max_length=1024)),
                ('positive', models.FloatField()),
                ('negative', models.FloatField()),
            ],
            options={
                'db_table': 'phone_opinions',
            },
        ),
    ]
