# Generated by Django 2.2.16 on 2020-10-17 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('valkyrie_phones', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phoneswithopinions',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
