# Generated by Django 2.2.16 on 2020-10-17 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('valkyrie_phones', '0002_auto_20201017_1340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phoneswithopinions',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
